name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs: []
## Broken when using test-py
#jobs:
#  validate:
#    runs-on: "ubuntu-latest"
#    steps:
#      - uses: "actions/checkout@v2"
#      - uses: home-assistant/actions/hassfest@master
