name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_requirements:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: Verify Hassfest type
        id: hassfest-verify
        run: |
          grep -E "require.*http.*test-files.pythonhosted.*#" custom_components/plugwise/manifest.json && echo hassfest-lite || echo hassfest
      - uses: home-assistant/actions/hassfest@master
        if: steps.hassfest-verify.outputs.stdout == "hassfest"

